게임오버창 만들기(#5)
yeeuniii/BrickBreaking pull request #3
Opened 2022-02-19 11:24 UTC by yeeuniii

점프점프 너무 어려워용

2022-02-19 11:32 UTC, parkchu commented
학생 점프 구현할수 있습니다 화이팅!! 😄

2022-02-19 11:33 UTC, parkchu commented
점프 작업 다 한다음에 해당 PR 다시 열면 될거 같아용

2022-02-20 15:25 UTC, yeeuniii commented
저 다 했는데 PR 다시 보내야하나여?

2022-02-20 15:27 UTC, parkchu commented
@yeeuniii 아뇨 PR 다시 열었어요~

2022-02-21 07:08 UTC, parkchu requested changes
고민한 흔적들이 많이 보이네요! 👍 
점프와 게임 오버 관련된 피드백은 저랑 짝프로그래밍 하면서 더 할게요!!

2022-02-21 07:08 UTC, parkchu commented on main.py
> +        self.color = THECOLORS[random.choice(["indianred4", "indianred3", "darksalmon"])]
랜덤으로 선택된 값은 파라미터로 받아도 되지 않을까요?

2022-02-21 07:08 UTC, parkchu commented on main.py
> +            group.remove(self)
이 함수는 벽돌 색깔을 바꿔주는 역할을 하는거 같은데 벽돌을 삭제하는 기능까지 수행하면 2가지 일을 하는거 아닐까요?

2022-02-21 07:08 UTC, parkchu commented on main.py
> +    def edge(self, screen):
edge 는 모서리 라는 뜻으로 알고 있어요.
함수명만 보고 해당 함수가 무슨일을 하는지 모르겠습니다. ㅠㅠ 
모서리에 부딪힐때 화면 밖으로 나가지 못하게 막아주는 함수 같은데 hit_edge, stop_edge 같은 함수명은 어떨까요?

2022-02-21 07:08 UTC, parkchu commented on test.py
> +import pygame
테스트 코드를 만들며 학습하신거 너무 잘했어요! 💯

2022-02-21 07:08 UTC, parkchu commented on main.py
> +from pygame.colordict import THECOLORS
중복된 코드를 지우기 위해 from을 잘활용했네요! 👍 
그런데 pygame 은 이미 불러왔으니 THECOLORS를 전역변수로 만들어 보는건 어떨까요?

2022-02-21 07:08 UTC, parkchu commented on main.py
> +    ordered_pair = []
ordered_pair 리스트는 어디서 사용되고 있는건가요?

2022-02-21 07:08 UTC, parkchu commented on main.py
> +def check1(dumbo, ball):
함수명에 test1, test2 와 같이 숫자로 구분지으면 어떤 차이가 있는지 찾기 힘들지 않을까요?

2022-02-21 07:08 UTC, parkchu commented on main.py
> +    time = 0
time 변수는 어떤일을 하는거죠?

2022-02-21 07:08 UTC, parkchu commented on main.py
> +        dumbo.speed, time = jump_or_not(time, dumbo)
점프 기능을 do_event 안에 넣지 않은 이유는 뭔가요?

2022-02-21 07:08 UTC, parkchu commented on main.py
> +        main()
main() 함수를 다시 실행시키는 것도 좋지만 최소한의 변수를 초기화 시켜서 게임을 다시 시작할 수 있지 않을까요?

2022-02-21 07:15 UTC, yeeuniii commented on main.py
> +        self.color = THECOLORS[random.choice(["indianred4", "indianred3", "darksalmon"])]
꼭 그렇게 해야 하는 이유가 있나요?

2022-02-21 08:13 UTC, yeeuniii commented on main.py
> +from pygame.colordict import THECOLORS
상수(변하지 않는 것)은 전역변수로 생성하는 게 좋음.
전역변수는 변수명을 대문자로 만들어야 함.

2022-02-21 08:14 UTC, parkchu commented on main.py
> +        self.color = THECOLORS[random.choice(["indianred4", "indianred3", "darksalmon"])]
클래스를 생성할때 임의의 값이 정해지면 테스트 코드를 작성할때 결과값이 변하기 때문입니다.

2022-02-21 08:33 UTC, parkchu requested changes

2022-02-21 08:33 UTC, parkchu commented on main.py
> +def ballndumbo_collision(dumbo, ball):
함수명은 동사 + 명사로 지어주세요.

2022-02-21 08:33 UTC, parkchu commented on main.py
> +def ballnbrick_collision(ball, element, group, points):
함수명은 동사 + 명사로 지어주세요.

2022-02-23 13:01 UTC, parkchu requested changes
코드 잘 구현했네요! 👍

2022-02-23 13:01 UTC, parkchu commented on main.py
> +        self.jumping = jumping
jumping 속성을 만들지 않아도 해결할 수 있지 않을까요?

2022-02-23 13:01 UTC, parkchu commented on main.py
> +            group.delete(self)
remove 와 delete 의 차이는 뭔가요?

2022-02-23 13:01 UTC, parkchu commented on main.py
> +    def delete(self, group):
group 에서 brick을 지우는거 같은데 이 함수가 Brick 클래스 안에 들어가야 할까요?

2022-02-23 13:05 UTC, yeeuniii commented on main.py
> +            group.delete(self)
둘 다 제거하다라는 의미긴 한데 pygame.sprite의 그룹에 remove라는 함수가 이미 있기때문에 차별화를 두기 위해 delete로 변경했는데, 저 자리에는 remove 함수가 쓰이는게 맞네용 ctrl+F6으로 함수명 고치다가 remove가 delete로 바뀌어버린거같애용 수정하도록 하겠습니당

2022-02-23 13:06 UTC, yeeuniii commented on main.py
> +    def delete(self, group):
Brick 클래스의 color 속성을 이용한 조건으로 그룹에서 지울지 여부를 결정하는 것이기 때문에 Brick 클래스 안의 메소드가 되는 게 적절하다고 생각했는데 그렇지 않은가요?

2022-02-23 13:12 UTC, parkchu commented on main.py
> +    def delete(self, group):
제거하는 일을 수행하는건 group 이 하고 있기 때문에 brick 에서는 해당 brick 이 제거되어야 하는지의 여부만 알아내는 함수를 만들어 사용하는게 좋을거 같아요 😄

2022-02-23 13:16 UTC, parkchu requested changes

2022-02-23 13:16 UTC, parkchu commented on main.py
> +    if key_type == pygame.K_SPACE and dumbo.speed[1] == 0:
dumbo 의 속성 값을 꺼내와야 할까요?

2022-02-23 13:41 UTC, parkchu requested changes

2022-02-23 13:41 UTC, parkchu commented on main.py
> +    for element in group:
해당 for문을 사용하지 않고 구현해보세요!

2022-02-23 13:41 UTC, parkchu commented on main.py
> +def check_dumbo_and_ball(dumbo, ball):
충돌 이벤트를 다루고 있는 함수가 무슨 일을 하는지 생각해보고 어디에 작성하면 좋을지 생각해보세요!

2022-02-23 13:43 UTC, parkchu requested changes

2022-02-23 13:43 UTC, parkchu commented on main.py
> +def delete_from_group(element, group):
Bricks 클래스를 만들어보면 어떨까요?

2022-02-23 14:45 UTC, yeeuniii commented on main.py
> +    for element in group:
이 부분을 for문을 사용하지 않고 어떤 식으로 해야 할 지 잘 모르겠습니다.
충돌검사를 group 안의 모든 원소에 대해서 진행해야하기때문에 for문을 사용한 건데, for문 말고 다른 방법으로 이게 가능 한가요? 그게 가능하다면 event의 경우도 for문을 사용하지 않아도 되는 거 아닌가요?

2022-02-24 07:23 UTC, yeeuniii commented on main.py
> +    if key_type == pygame.K_SPACE and dumbo.speed[1] == 0:
클래스의 속성을 이용해서 값 처리를 하는 경우에는 대부분 클래스 안에서 처리할 수 있기 때문에, 메소드를 만들어서 하는 게 더 좋은 방법. 
클래스 = 하나의 물체 
메소드 = 물체에 대한 상태 질문, 행동

2022-02-24 08:31 UTC, yeeuniii commented on main.py
> +        self.image.fill(self.color)
인자를 받아서 클래스의 속성을 변경해주는 방법 지향

2022-02-25 14:26 UTC, parkchu requested changes
again 버튼을 누른 후에 게임 오버가 되면 again 이나 end 버튼을 클릭하지 않아도 마우스 커서의 위치에 따라 버튼이 눌러지게 됩니다. 해당 오류도 같이 수정해주세요! 😄

2022-02-25 14:26 UTC, parkchu commented on main.py
> +        return not self.rect.bottom >= screen.get_height()
not 을 사용하지 않고 구현할 수 있지 않을까요?

2022-02-25 14:26 UTC, parkchu commented on main.py
> +    press_space_key(key, dumbo)
dumbo.move_left, dumbo.move_right 는 덤보야! 왼쪽으로 움직여!! 또는 덤보야! 오른쪽으로 움직여!! 라고 해석이되는 함수 같아요! 이런 함수들은 호출될때 무조건 할당된 일을 수행하도록 구현하는게 좋지 않을까요?

2022-02-25 14:26 UTC, parkchu commented on main.py
> +        show_ending(screen, bricks.broken_number)
엔딩 화면은 한번만 보여주면 되는거 아닌가요?

2022-02-25 14:59 UTC, parkchu requested changes

2022-02-25 14:59 UTC, parkchu commented on main.py
> +        dumbo.move_left(key)
이 함수는 왜 만든건가요?

2022-02-25 15:10 UTC, yeeuniii commented on main.py
> +        dumbo.move_left(key)
함수 쪼개기..?

2022-02-25 15:12 UTC, parkchu commented on main.py
> +        dumbo.move_left(key)
이 함수를 만들지 않고도 구현가능한데 쪼갠 이유가 뭔가요?

2022-02-25 15:13 UTC, yeeuniii commented on main.py
> +        dumbo.move_left(key)
함수가 하나의 기능을 하면 좋다고 들었슴다.

2022-02-25 16:02 UTC, parkchu approved these changes
코드 잘 구현했어요. 💯 
힘들고 어려운 미션들인데 끝까지 노력해줘서 고마워요 😄

2022-02-25 16:02 UTC, merged